
name: Azure App Service Deploy

on:
  push:
    branches:
      - main  # change to 'master' if that's your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build React app
        run: |
          cd frontend
          npm run build
          mkdir -p ../backend/frontend
          mv build ../backend/frontend/

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: weather-wardrobe  # ✅ your app name
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_379E0CE115104B8187FE2A741E93E9D1 }}

          package: ./backend


